theme: "jekyll-theme-hacker"
locale: "zh-TW"
title: "人工智慧與工程應用課程 2021"
name: "人工智慧與工程應用課程 2021"
description: "本課程探討人工智慧（AI）與工程應用相關議題，並討論解決方法與技術發展趨勢。內容由淺入深包含基礎 Python 程式設計、資料預處理、資料探索、機器學習、深度學習、AI 工程應用介紹及專題製作。學生可由本課程了解 AI 之基本原理，及 AI 在工程上的應用，以作為進入產業後了解如何導入人工智慧於產業應用之中，提昇工程背景學生 AI 應用及程式設計的技能。"

github:
  repository_name: "人工智慧與工程應用課程 2021"

logo: "/images/logo.png"
image: "/images/logo.png"
